#! /bin/bash

set -e -x

if [ -z "${H2O_BRANCH}" ]; then
    echo "H2O_BRANCH must be set"
    exit 1
fi

cd ~

git clone https://github.com/h2oai/h2o-flow

cd h2o-flow

git checkout ${H2O_BRANCH}
make install

cd ..
rm -rf h2o-flow
