export const whitespaceSeparators = [
  'NULL',
  'SOH (start of heading)',
  'STX (start of text)',
  'ETX (end of text)',
  'EOT (end of transmission)',
  'ENQ (enquiry)',
  'ACK (acknowledge)',
  'BEL \'\\a\' (bell)',
  'BS  \'\\b\' (backspace)',
  'HT  \'\\t\' (horizontal tab)',
  'LF  \'\\n\' (new line)',
  'VT  \'\\v\' (vertical tab)',
  'FF  \'\\f\' (form feed)',
  'CR  \'\\r\' (carriage ret)',
  'SO  (shift out)',
  'SI  (shift in)',
  'DLE (data link escape)',
  'DC1 (device control 1) ',
  'DC2 (device control 2)',
  'DC3 (device control 3)',
  'DC4 (device control 4)',
  'NAK (negative ack.)',
  'SYN (synchronous idle)',
  'ETB (end of trans. blk)',
  'CAN (cancel)',
  'EM  (end of medium)',
  'SUB (substitute)',
  'ESC (escape)',
  'FS  (file separator)',
  'GS  (group separator)',
  'RS  (record separator)',
  'US  (unit separator)',
  '\' \' SPACE',
];
